---
policy_selector:
  static:
    policy: ocis
policies:
  - name: ocis
    routes:
      - endpoint: "/"
        backend: http://web:9100
      - endpoint: "/.well-known/"
        backend: http://idp:9130
      - endpoint: "/konnect/"
        backend: http://idp:9130
      - endpoint: "/signin/"
        backend: http://idp:9130
      - type: regex
        endpoint: "/ocs/v[12].php/cloud/(users?|groups)"
        backend: http://ocs:9110
      - endpoint: "/ocs/"
        backend: http://storage-frontend:9140
      - type: query
        endpoint: "/remote.php/?preview=1"
        backend: http://webdav:9115
      - endpoint: "/remote.php/"
        backend: http://storage-frontend:9140
      - endpoint: "/dav/"
        backend: http://storage-frontend:9140
      - endpoint: "/webdav/"
        backend: http://storage-frontend:9140
      - endpoint: "/status.php"
        backend: http://storage-frontend:9140
      - endpoint: "/index.php/"
        backend: http://storage-frontend:9140
      - endpoint: "/data"
        backend: http://storage-frontend:9140
      - endpoint: "/app/"
        backend: http://storage-frontend:9140
      - endpoint: "/archiver"
        backend: http://storage-frontend:9140
      - endpoint: "/graph/"
        backend: http://graph:9120
      - endpoint: "/graph-explorer/"
        backend: http://graph-explorer:9135
      - endpoint: "/api/v0/accounts"
        backend: http://accounts:9181
      - endpoint: "/accounts.js"
        backend: http://accounts:9181
      - endpoint: "/api/v0/settings"
        backend: http://settings:9190
      - endpoint: "/settings.js"
        backend: http://settings:9190
